### ISSUE TITLE
Chrome offline flags?

### ISSUE THREAD

**Issue by orschiro** [rahiel/archiveror#10]
Dear @rahiel,

Just a quick question to enhance my understanding. Do the following chrome:flags make the use of Archiveror obsolete?

![image](https://cloud.githubusercontent.com/assets/170947/15807128/7747d8b4-2b55-11e6-93bb-6faab72c324f.png)

Thankfully,

~Robert

**Comment by rahiel** [comment]
Dear @orschiro, I didn't know of these flags, they look handy. As I understand it, these use Chromium's (volatile) cache so it does not have every page you've ever visited, because it deletes some of them to prevent saving the whole internet on your hard disk (see [disk cache](https://www.chromium.org/developers/design-documents/network-stack/disk-cache)).

Archiveror makes non-volatile copies of your bookmarks. I think Chromium tracks which pages you visit often to decide which to keep in cache, but it doesn't guarantee anything. I'd advise to disable Archiveror for a while, and if see if these flags do make it obsolete for you?

**Comment by orschiro** [comment]
Dear @rahiel,

I've been testing the flags with [this HTML editor demo](https://www.froala.com/wysiwyg-editor) and it is working great so far:

https://www.youtube.com/watch?v=xpuMgCrekiA

The only downside might indeed be the cache in that it might not save a cached version for all bookmarked pages. 

But for these cases there is Archiveror available then. :smiley: 

~Robert

**Comment by rahiel** [comment]
Sweet!
