### ISSUE TITLE
Automatically archive bookmarks don't work.

### ISSUE THREAD

**Issue by mikhoul** [rahiel/archiveror#32]
I've enabled "Automatically archive bookmarks" but it don't work ?

![image](https://user-images.githubusercontent.com/5678673/47932162-472f7f80-dea7-11e8-939d-7cbba94d275e.png)

![image](https://user-images.githubusercontent.com/5678673/47932226-747c2d80-dea7-11e8-8340-f56a3ebc7dc1.png)

----------------------------------------------------------------------------------------------------------

Also I have a request I'd really like to be able to move the "Archived URLs" from "Other bookmarks" in another place  so it would not clutter my "Bookmarks bar" making visible the "Other bookmarks" shortcut to show up.

The  "Other bookmarks" don't show up when it is empty and since you place the "Archived URLs"  inside the "Other bookmarks" it show up on the "bookmarks bar" taking valuable space.

So being able to put/move "Archived URLs" another place will be very useful for Chromium users.

Chromium | 68.0.3440.106 (Build officiel) (32 bits)
-- | --
Révision | 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
Système d'exploitation | Windows

If you need more information just ask me

Regards :octocat:

**Comment by rahiel** [comment]
Hi, thanks for making a comprehensive bug report.

The "Archived URLs" directory is not made or managed by Archiveror, you can safely delete it as it has nothing to do with this extension.

I cannot reproduce the bug where auto archiving doesn't work. Could you first remove Archiveror and reinstall it: https://chrome.google.com/webstore/detail/archiveror/cpjdnekhgjdecpmjglkcegchhiijadpb.

Because I cannot reproduce this, could you find the error by doing the following:
Go to: Options -> More Tools -> Extensions. At the top right enable the switch for "Developer mode". Then in the Archiveror block you'll see a link called "background page". Click on it and in the new window that appears, click on "Console". Then finally bookmark a page (with auto archiving enabled), and if there is an error, you should see it appear in the console. Please copy the errors and paste them here.

**Comment by mikhoul** [comment]
I tried but I don't see any error I even tried on another chrome installation but sadly it's the same results and no error in the console.

Could you tell me where the bookmarks are supposed to be saved exactly ? 

Note: The "Archived URLs" folder was from another extension with the same purpose, it was a mistake from me.

**Comment by rahiel** [comment]
You have to make a bookmark, and then a small yellow "!" appears in the Archiveror toolbar icon. Clicking on it shows a popup with at the bottom links to the archives for the page.

You make the bookmarks wherever you want, then Archiveror saves the archive links in its own storage.

**Comment by mikhoul** [comment]
Ahhhhh that's why I was so confused because I used to use addons/extensions that saved automatically bookmarks when I was saving them with "Archive websites"....
