### ISSUE TITLE
auto-archiving of new pages on archive.is is broken

### ISSUE THREAD

**Issue by rahiel** [rahiel/archiveror#34]
When a page that isn't yet on archive.is gets auto-archived, the wrong link is captured and saved. The URL `https://archive.is/submit/` is saved now.

**Comment by chrisjj** [comment]
I'm finding the same on the latest version.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Thank you for your graet extension.
it is really a relief know that it is doing its work in background :)
Specially for someone like me that bookmarks alot pages.

I also saw this several times
i don't sure but may be it is because Archive.is changed its main domain and encourage to use new domain instead of .is one?

(https://web.archive.org/web/20190106000101/https://twitter.com/archiveis/status/1081276424781287427)

**Comment by rahiel** [comment]
Hey @3j9fkyahunqoxwqu, I'm happy you like the extension.

I'm currently working on this issue, I hope to have it fixed soon. And thanks for the suggestion, I'll look at using the new domain.

**Comment by rahiel** [comment]
Fixed in https://github.com/rahiel/archiveror/commit/0ea87f7498b0a6090e310cb1f057b2e336082f4b, you'll get this fix when your browser next updates your extensions.
