### ISSUE TITLE
Archive web apps?

### ISSUE THREAD

**Issue by orschiro** [rahiel/archiveror#9]
Dear @rahiel, 

Just a quick question:

Is it possible to archive a web app locally (i.e. access offline) that has some interactive functionality?

Example: http://wikitable.eu5.org/

I would love to take this editor with me while being offline! 

Thankfully,

~Robert

**Comment by rahiel** [comment]
Hey @orschiro, this is not possible with Archiveror now. Chromium doesn't save javascript in the local MHTML files, it also disallows loading of external content from `file://` pages.

But it is still possible, I tried something with wget. First navigate your shell to where you want to save the files, then:

```bash
wget -p -H -k http://wikitable.eu5.org/
python3 -m http.server
```

And navigate in your browser to http://0.0.0.0:8000/wikitable.eu5.org/. I'm not sure if this will work for all websites, wget has many options and it might need some tweaking, you can see [here](http://stackoverflow.com/a/6510193) the wget options we used. That python command starts a local webserver, because otherwise the browser would block external resources (here just scripts in another folder) if you'd open it directly with `file://`. 

It may also be worth looking at http://www.httrack.com/. I found it after I realized that this local archiving via a browser extension is kind of crazy.

**Comment by orschiro** [comment]
Hi @rahiel,

  

Thanks for your wget workaround. This is working very well!

  

&gt; It may also be worth looking at http://www.httrack.com/. I found it after
I realized that this local archiving via a browser extension is kind of crazy.

  

Well, for me the charm of your extension lies in the fact that it does all the
archiving automatically.

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 9 2016, at 10:45 pm, Rahiel Kasim &lt;notifications@github.com&gt;
wrote:  

> Hey [@orschiro](https://github.com/orschiro), this is not possible with
Archiveror now. Chromium doesn't save javascript in the local MHTML files, it
also disallows loading of external content from file:// pages.

>

> But it is still possible, I tried something with wget. First navigate your
shell to where you want to save the files, then:

>  
>  
>     wget -p -H -k http://wikitable.eu5.org/

>     python3 -m http.server

>

> And navigate in your browser to <http://0.0.0.0:8000/wikitable.eu5.org/>.
I'm not sure if this will work for all websites, wget has many options and it
might need some tweaking, you can see
[here](http://stackoverflow.com/a/6510193) the wget options we used. That
python command starts a local webserver, because otherwise the browser would
block external resources (here just scripts in another folder) if you'd open
it directly with file://.

>

> It may also be worth looking at <http://www.httrack.com/>. I found it after
I realized that this local archiving via a browser extension is kind of crazy.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/rahiel/
archiveror/issues/9#issuecomment-207852060)![](https://github.com/notification
s/beacon/AAKbw-mg0jgvXsqjx4jzTQ3l-eV1UUqCks5p2A_7gaJpZM4IDpfG.gif)

**Comment by rahiel** [comment]
> Well, for me the charm of your extension lies in the fact that it does all the archiving automatically.

:smile: 

I thought about letting the extension communicate with an external program to manage the archives for more flexibility. But the simplest solution often wins.
